### ISSUE TITLE
What the usage of `mime` in `File`?

### ISSUE THREAD

**Issue by Berrysoft** [Tim-Paik/FRFS#1]
https://github.com/Tim-Paik/FRFS/blob/a4efaa0b8941c922203bfc40f57be4d613bb5122/src/lib.rs#L113

It seems that nowhere uses this field.

**Comment by Tim-Paik** [comment]
I originally created this crate to bundle web files and then serve http from a single frfs, so I needed mime, because most browsers won't work without correct mime

**Comment by Berrysoft** [comment]
`mime` is not public, and I think it is not a usual filesystem feature. I suggest removing it.
