### ISSUE TITLE
What's `from_embed_file` for?

### ISSUE THREAD

**Issue by Berrysoft** [Tim-Paik/FRFS#2]
https://github.com/Tim-Paik/FRFS/blob/a4efaa0b8941c922203bfc40f57be4d613bb5122/src/lib.rs#L466-L470

It loads a file and copy them to a new temp file. I wonder what is it for.

It would be better to expose an API which simply loads a file and don't copy it. It's up to user to determine whether to copy it.

**Comment by Tim-Paik** [comment]
Using this API is as simple as the first line of your code:
https://github.com/Tim-Paik/FRFS/blob/a4efaa0b8941c922203bfc40f57be4d613bb5122/src/lib.rs#L465
It is used to load frfs embedded in frfs
