### ISSUE TITLE
Feature: add `vfs` support

### ISSUE THREAD

**Issue by Berrysoft** [Tim-Paik/FRFS#4]
A such use case is here: https://github.com/Uni-Gal/Ayaka/pull/57

We can add it as a feature. `FRFS` is very much like `vfs` and it is easy to support it.

**Comment by Tim-Paik** [comment]
As you can see, the full name of FRFS is File-based Read-only File System, which is read-only.
So I can only implement the read part of the vfs, do you have any ideas?

**Comment by Berrysoft** [comment]
Just implementing the readonly part is fine.

https://github.com/Berrysoft/Ayaka/blob/dev/tar/utils/ayaka-runtime/src/pack.rs

**Comment by Tim-Paik** [comment]
added in https://github.com/Tim-Paik/FRFS/commit/bb25b613629515c376cff9adae4638771a2278bd
